modLoader="kotlinforforge"
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="processingage"
version="${file.jarVersion}"
displayName="Processing Age"
logoFile="processingage.png"
authors="jrddunbr"
description='''
This is Processing Age. It's designed to allow for ore processing and materials processing.
'''
[[dependencies.processingage]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.processingage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
